apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-llama2-gpu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Specify the desired storage size
