apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-llama2-gpu
  name: k8s-llama2-gpu-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-llama2-gpu
  sessionAffinity: None
  type: ClusterIP
